### ISSUE TITLE
const/type Cannot find name '***'

### ISSUE THREAD

**Issue by fengshenhai-0727** [Microsoft/TypeScript-React-Starter#119]
![image](https://user-images.githubusercontent.com/23276885/36010104-9e700ce0-0d8a-11e8-85f2-d32a740d91a8.png)
![image](https://user-images.githubusercontent.com/23276885/36010110-a6b1c84e-0d8a-11e8-967c-185274d514d7.png)

**Comment by DanielRosenwasser** [comment]
Doesn't look related to this repo since you've set up your own path mapping. If anything it's a TypeScript bug.
