### ISSUE TITLE
npm run gives error "--watch is not supported without git/hg...ERR! code ELIFECYCLE"

### ISSUE THREAD

**Issue by user135711** [Microsoft/TypeScript-React-Starter#128]
npm run test gives me the error: 

> Determining test suites to run...
> --watch is not supported without git/hg, please use --watchAll
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! my-app2@0.1.0 test: `react-scripts-ts test --env=jsdom`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the my-app2@0.1.0 test script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2018-03-26T05_52_03_465Z-debug.log

Versions: node v9.9.0, npm  v5.6.0

**Comment by nineonine** [comment]
change line 31 in ```/node_modules/react-scripts-ts/scripts/test.js```

 from

```
argv.push('--watch');
```

to

```
argv.push('--watchAll');
```

this should solve the problem.

**Comment by user135711** [comment]
@nineonine That worked. Should I close this as a problem particular to my set up or should someone submit a pull request? So I can debug myself in the future, how did you know the error was that file, and that line?

**Comment by nineonine** [comment]
@user135711  the first line of error output indicates that there is something wrong with ```watch/watchAll``` . It also mentions  ```react-scripts-ts``` so I experimented and that paid off.

**Comment by porkopek** [comment]
Running "git init", it should work. No need to change any line of code

**Comment by primaulia** [comment]
why tho @porkopek ?

**Comment by DanielRosenwasser** [comment]
Instructions should now make this explicit.
