### ISSUE TITLE
JSX element type 'App' is not a constructor

### ISSUE THREAD

**Issue by tomabecea** [Microsoft/TypeScript-React-Starter#13]
Following the readme tutorial, after changing the original render function to render the new 'Hello' component, the error is 
>    (7,3): error TS2605: JSX element type 'App' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => void | Element | Component<any, ComponentState>' is not assignable to type '() => Element | null'.
      Type 'void | Element | Component<any, ComponentState>' is not assignable to type 'Element | null'.
        Type 'void' is not assignable to type 'Element | null'.

The code is

    class App extends React.Component<{}, null> {
        render() {
            return ReactDOM.render(
                <Hello name="TypeScript" enthusiasmLevel={10} />,
                document.getElementById('root') as HTMLElement
            );
        }
    }

Visual Studio Code 1.12.1
TypeScript React 2.3.2
npm 3.10.10

**Comment by semlette** [comment]
There are a few mistakes in your code.

1)
In React you must render *one* root component with `ReactDOM.render`. In this case, that would be your `App` component. So outside of the component, call `ReactDOM.render` on the `App` component like this:

```typescript
class App extends React.Component<{}, null> {
    /* ... */
}

ReactDOM.render(
    <App />,
    document.getElementById('root') as HTMLElement
);
```

2)
React components' `render` method must return a JSX element or component, in your case, the `Hello` component.
```typescript
class App extends React.Component<{}, null> {
    render() {
        return (
            <Hello name="TypeScript" enthusiasmLevel={10} />
        );
    }
}
```

**Comment by tomabecea** [comment]
Yeap, great! Still an error here ('React' refers to a UMD global, but the current file is a module) but it has workarounds. Thanks.
