### ISSUE TITLE
Expected 4 type arguments, but got 1.

### ISSUE THREAD

**Issue by haani104** [Microsoft/TypeScript-React-Starter#140]
I am getting this error can anyone help ?

<img width="603" alt="screen shot 2018-04-27 at 19 29 06" src="https://user-images.githubusercontent.com/6011865/39362641-63b6881e-4a51-11e8-9845-553503591699.png">

This is the type definition of IStoreState
```
export interface IStoreState {
    languageName: string;
    enthusiasmLevel: number;
}
```

**Comment by etlolap** [comment]
Is it duplicate to https://github.com/Microsoft/TypeScript-React-Starter/issues/136?

**Comment by haani104** [comment]
Not sure if this is the solution to it, but this worked for me

I imported EnthusiasmAction

import { EnthusiasmAction } from './actions/index';
and used like below

const store = createStore<IStoreState, EnthusiasmAction, any, any>(enthusiam, {
  enthusiasmLevel: 1,
  languageName: 'TypeScript'
});

**Comment by QingNote** [comment]
If don't know what the type is, try to describe it as 'any'
const store = createStore<StoreState,any,any,any>(enthusiasm, {
    enthusiasmLevel: 1,
    languageName: 'TypeScript',
});

**Comment by Vlad412** [comment]
Didn't work, why it's closed and readme not updated

**Comment by gonzarodriguezt** [comment]
The solution presented by @haani104 is good, but for me was incomplete, i had to make tihis change in my `/reducers/index.tsx`:

```typescript
import { Reducer } from "redux";

export const enthusiasm: Reducer = (
  state: StoreState,
  action: EnthusiasmAction
): StoreState => {
  switch (action.type) {
    case INCREMENT_ENTHUSIASM:
      return { ...state, enthusiasmLevel: state.enthusiasmLevel + 1 };
    case DECREMENT_ENTHUSIASM:
      return { ...state, enthusiasmLevel: state.enthusiasmLevel - 1 };
  }
  return state;
};
```

Basically, createStore expects a function of type Reducer as one of it arguments, and in the tutorial, we are declaring it as a plain function.
