### ISSUE TITLE
table specific attributes

### ISSUE THREAD

**Issue by yesil** [Microsoft/TypeScript-React-Starter#15]
If I change the Hello.tsx content as follows, 
```
  <table align="center"><tr><td>

    <div className="hello">
      <div className="greeting">
        Hello {name + getExclamationMarks(enthusiasmLevel)}
      </div>
      <div>
        <button onClick={onDecrement}>-</button>
        <button onClick={onIncrement}>+</button>
      </div>
    </div>

  </td></tr></table>
```

I get the following error:

Failed to compile.

Error in ./src/components/Hello.tsx
(17,10): error TS2339: Property 'align' does not exist on type 'HTMLProps<HTMLTableElement>'.
I noticed the same behaviour with latest TypeScript 2.3.2 on a different project as well.

**Comment by infeng** [comment]
Do not use this attribute, as it has been deprecated.

**Comment by yesil** [comment]
@infeng we are generating email client compatible markups and unfortunately we need to use all those deprecated attributes...  
Also the `align` attribute seems to be supported by typescript, see: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L6508

**Comment by infeng** [comment]
The type of `table` is `React.HTMLProps<HTMLTableElement>`, `HTMLTableElement` is generics, see:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L457

**Comment by yesil** [comment]
Thanks, done at https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16693.
