### ISSUE TITLE
Problems with StoreState

### ISSUE THREAD

**Issue by a455047** [Microsoft/TypeScript-React-Starter#182]
\TypeScript-React-Starter\src\**index.tsx** has problem with const store = **createStore<StoreState>**

Error '(12,27): Expected 4 type arguments, but got 1.'

**Comment by geekyme** [comment]
https://github.com/Microsoft/TypeScript-React-Starter/issues/140

**Comment by JamesSkemp** [comment]
Saw that issue before I kept digging, and I'm wondering if a) that's the correct solution and the tutorial needs to be updated or b) the individual accidentally closed the issue when making their comment and the tutorial still needs to be updated with the correct solution.

**Comment by a455047** [comment]
I tried solution from #140, but doesn't work unless I'm missing something...
see original error and updated/modified version attached

![27-08-18 10 10 59 am](https://user-images.githubusercontent.com/21300508/44634810-f3c42100-a98d-11e8-8e3d-71375d07d459.png)
![27-08-18 10 10 24 am](https://user-images.githubusercontent.com/21300508/44634811-f45cb780-a98d-11e8-9f3c-ccadf50ea3e3.png)

**Comment by JamesSkemp** [comment]
@a455047 you have `IStoreState` instead of just keeping `StoreState`. I think that might fix one of the errors.

**Comment by a455047** [comment]
Thanks James.

I just followed https://github.com/Microsoft/TypeScript-React-Starter/issues/140#issuecomment-385237886 as it was prompted, so I copied 
const store = createStore<IStoreState, EnthusiasmAction, any, any>(enthusiam, {
 enthusiasmLevel: 1,
 languageName: 'TypeScript'
 });

Anyway, changing from IStoreState to StoreState didn't fix the issue, see attached.
![28-08-18 10 52 18 am](https://user-images.githubusercontent.com/21300508/44694461-107b5a00-aa5d-11e8-80cd-db2ae4447aab.png)

**Comment by a455047** [comment]
Thanks James! See updated working version below:

import * as React from 'react';
import * as ReactDOM from 'react-dom';

import Hello from './containers/Hello';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import { enthusiasm } from './reducers/index';
import { StoreState } from './types/index';

import './index.css';

import { EnthusiasmAction } from './actions/index';

const store = createStore<StoreState, EnthusiasmAction, any, any>(enthusiasm, {
  enthusiasmLevel: 1,
  languageName: 'TypeScript'
  });
  

ReactDOM.render(
  <Provider store={store}>
    <Hello />
  </Provider>,
  document.getElementById('root') as HTMLElement
);

Cheers

**Comment by mdgrech** [comment]
The solution above works for me but I thought using any was a no no?

**Comment by bhellema** [comment]
What's the current state of this solution?  Working through a broken demo is discouraging.

**Comment by tpetrina** [comment]
You can just wait for https://github.com/facebook/create-react-app/pull/4837 to be finished and just use TypeScript natively with CRA 2.
