### ISSUE TITLE
404 Not Found: react-script-ts@latest

### ISSUE THREAD

**Issue by etherwizard** [Microsoft/TypeScript-React-Starter#188]
Attempting to run this command after installing create-react-app with the global flag:

_create-react-app my-react-app --scripts-version=react-script-ts_

This results in the following:

**npm ERR! code E404
npm ERR! 404 Not Found: react-script-ts@latest**

I can confirm that react-script-ts is no longer available on NPM.

@Microsoft : Please update this repository.

**Comment by Ebuall** [comment]
its react-script**s**

**Comment by kiwanska** [comment]
Hah, this answer made me look again at my command and find typo as well, ❤️
