### ISSUE TITLE
create-react-app support TypeScript now!

### ISSUE THREAD

**Issue by Taym95** [Microsoft/TypeScript-React-Starter#218]
I think we should remove `create-react-app my-app --scripts-version=react-scripts-ts` because the new create-react-app version support TypeScript.

**Comment by johot** [comment]
But it's not released yet right? Heard it would be in version 2.1 of CRA?

**Comment by JLarky** [comment]
CRA uses babel transpiler which still has some [important limitations](https://github.com/wmonk/create-react-app-typescript/pull/409#issuecomment-429517335), so as it is right now CRA won't replace react-scripts-ts in general case.

**Comment by Timer** [comment]
PR up in https://github.com/Microsoft/TypeScript-React-Starter/pull/227
