### ISSUE TITLE
react-scripts-ts is vulnerable

### ISSUE THREAD

**Issue by JukoPowel** [Microsoft/TypeScript-React-Starter#250]
react-scripts-ts newest version uses webpack-dev-server@3.1.9, which is vulnerable version.
There is no public repository for react-scripts-ts, so I report it here, since You recommend to use this package.

**Comment by TomasHubelbauer** [comment]
This is the repository you are referring to: https://github.com/wmonk/create-react-app-typescript

**Comment by JukoPowel** [comment]
Thank You for quick response.
I found useful migration guide:
https://vincenttunru.com/migrate-create-react-app-typescript-to-create-react-app/

Issue may be closed.

**Comment by gasparsigma** [comment]
Hi Tomas, the README.md still refers to `create-react-app my-app --scripts-version=react-scripts-ts` which will installl `react-scripts-ts` which still has the vulnerability. It should be updated to `create-react-app my-app --typescript` like you said, but then the guide will not match with the files generated, it should still be addressed.
