### ISSUE TITLE
Update readme to new way of configuring React TS project using CRA

### ISSUE THREAD

**Issue by JulianKowalczuk** [Microsoft/TypeScript-React-Starter#251]
Since create-react-app-typescript is obsoleted and react-scripts-ts vulnerable, it would be nice to update readme.

I found useful article, which may be helpful:
https://vincenttunru.com/migrate-create-react-app-typescript-to-create-react-app/

**Comment by TomasHubelbauer** [comment]
I think we should only keep #246 as this one duplicates it (is newer), but it would be useful to copy the guide link over to the other one.
