### ISSUE TITLE
Why `export const INCREMENT_ENTHUSIASM` then `export type INCREMENT_ENTHUSIASM`  again

### ISSUE THREAD

**Issue by yeongjet** [Microsoft/TypeScript-React-Starter#275]
![image](https://user-images.githubusercontent.com/7941297/55936530-2692ff00-5c69-11e9-8cd2-d7902768eba9.png)
Why `export const INCREMENT_ENTHUSIASM` then `export type INCREMENT_ENTHUSIASM`  again, what's the meaning?

**Comment by phatnguyenuit** [comment]
You can open [`src/actions/index.tsx`](https://github.com/Microsoft/TypeScript-React-Starter/blob/master/src/actions/index.tsx) to understand more.

**Comment by alaneparisot** [comment]
Hi @yeongjet, have a look at [typeof type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#typeof-type-guards) and [string literal types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#string-literal-types).

Basically, it means a variable that has the type `INCREMENT_ENTHUSIASM` can only has `'INCREMENT_ENTHUSIASM'` as a value (in other words, it can't only be a string, it must also has this specific text as a value).

It's the same as writing `export type INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM'`.

On line 2 _value_ `INCREMENT_ENTHUSIASM` is exported.
On line 3 _type_ `INCREMENT_ENTHUSIASM` is exported.

TypeScript is smart enough to know when a variable is used as a value, and when it is used as a type.
