### ISSUE TITLE
Components / Functions have no returned type

### ISSUE THREAD

**Issue by Maxwell2022** [Microsoft/TypeScript-React-Starter#28]
Just looking at [`Hello.tsx`](https://github.com/Microsoft/TypeScript-React-Starter/blob/master/src/components/Hello.tsx), but it's the same everywhere

All functions in this example have no returned type, is there a reason why? Should this example goes all the way in to demonstrate Type Checking?

**Comment by DanielRosenwasser** [comment]
No, there's not really a point to it since inference will pick up the slack.

If you're writing a library with a stable API, it might make more sense to ensure you have explicit return types, but otherwise it comes down to personal preference.
