### ISSUE TITLE
Please abandon this repo

### ISSUE THREAD

**Issue by chriskuech** [microsoft/TypeScript-React-Starter#282]
`create-react-app` now officially supports TypeScript.  While this repo was clearly the best solution at the time, it no longer has benefit over the official `create-react-app` solution.  There are clearly many people struggling to still use this repo, despite it not having been updated in 2 years (an eternity in JS world).

**Comment by jamestharpe** [comment]
Maybe link to instructinos for creating an equivelent app using the "current" preferred method?

**Comment by chriskuech** [comment]
These are the official instructions provided by React team: 
https://facebook.github.io/create-react-app/docs/adding-typescript

**Comment by akilman** [comment]
Seconded

A disclaimer at the top of the readme would do

**Comment by karlhorky** [comment]
Maybe [archiving the repo](https://help.github.com/en/articles/archiving-a-github-repository) would also be a good idea.

**Comment by orta** [comment]
I agree, this is a great case of being able to redirect to the official docs. Let me take some time to audit the issues/PRs/code before making the final call but I agree from a cursory look.

**Comment by orta** [comment]
Alright, this is getting archived - thanks folks
