### ISSUE TITLE
Install fails on incorrect typings version for React

### ISSUE THREAD

**Issue by corydeppen** [Microsoft/TypeScript-React-Starter#3]
The dependency version for `@types/react` is listed as 5.0.14 in `package.json`, which causes an error during the install because it's not a valid target. The current version is 15.0.24, unless you meant to lock it to a prior release (15.0.14?).

**Comment by jpggvilaca** [comment]
React and @types/react are two different things. @types/react -> https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react and react ->https://github.com/facebook/react

So the versions are correct, and I haven't found any errors, can you show me steps to reproduce?

**Comment by corydeppen** [comment]
The version listed in `package.json` for the React typings is not valid. If you run `npm i @types/react@5.0.14` you'll see a message stating `No compatible version found: @types/react@5.0.14`, followed by a list of valid install targets - `5.0.14` is not one of them, but `15.0.14` is. Simple to fix, but not sure what the intent was when originally installed.

**Comment by nitishdayal** [comment]
To reproduce: make fresh clone of repo, npm install.Listed version in package.json is "5.0.14", which has never been a version number of the @types/react package. Releases have ranged from 0.0.0 > 0.14.57, then 15.0.0-latest. Latest release of React type defs is 15.0.24, which works fine w/ this starter when installed to replace the broken version that's currently listed.

**Comment by corydeppen** [comment]
PR #16 should resolve this.

**Comment by tebeco** [comment]
@corydeppen issue is still open ?

**Comment by corydeppen** [comment]
Should be resolved now that #16 has been merged.
