### ISSUE TITLE
What does "change up" mean?

### ISSUE THREAD

**Issue by FrankHealy** [Microsoft/TypeScript-React-Starter#33]
"and then change up our render call:

ReactDOM.render(
  <Hello name="TypeScript" enthusiasmLevel={10} />,
  document.getElementById('root') as HTMLElement
);"

Do I replace the render function with above, if so do I not need to import ReactDOM?

**Comment by 3ygun** [comment]
@FrankHealy only just went through the tutorial myself however in `index.tsx` the "change up" refers to your change from:

```tsx
ReactDOM.render(
  <App />,
  document.getElementById('root') as HTMLElement
);
```

to

```tsx
ReactDOM.render(
  <Hello name="TypeScript" enthusiasmLevel={10} />,
  document.getElementById('root') as HTMLElement
);
```

or later to

```tsx
ReactDOM.render(
  <Provider store={store}>
    <Hello />
  </Provider>,
  document.getElementById('root') as HTMLElement
);
```

My imports only changed in that I removed the `App` import and added the `Hello`, then `Provider`, etc. imports

This worked for my but your mileage may vary
