### ISSUE TITLE
I'm getting errors with Redux example

### ISSUE THREAD

**Issue by eriknyk** [Microsoft/TypeScript-React-Starter#49]
I'm trying to define constants like on the following example:

![image](https://user-images.githubusercontent.com/205721/28340738-6a9f1254-6bd6-11e7-9f2a-ceb18ee44a11.png)

my code:
![image](https://user-images.githubusercontent.com/205721/28340844-d4d361c0-6bd6-11e7-9d46-ce3d8ad8a42f.png)

And I'm trying to define the actions, however I'm getting the following error:

![image](https://user-images.githubusercontent.com/205721/28340790-a6313c7a-6bd6-11e7-8896-5b7191dd5fdc.png)

I'm just following the example on README, any help will be appreciated. 
Best Regards.

**Comment by corydeppen** [comment]
Looks like you're referencing _ENTHUSIAMS where it should be _ENTHUSIASM.

**Comment by eriknyk** [comment]
I'm an idiot, thank you @corydeppen
