### ISSUE TITLE
How to support hot reload?

### ISSUE THREAD

**Issue by Lxxyx** [Microsoft/TypeScript-React-Starter#6]
This project is useful, but how to use hot reload?

**Comment by jaredpalmer** [comment]
Just drop this into your index.tsx 

```
if (module.hot) {
  module.hot.accept();
}
```

**Comment by Lxxyx** [comment]
@jaredpalmer Thank you. Simple and useful. But when hot reload start, component state will be set to default state, how to resolve this problem?
May be I should stackoverflow this problem first.

**Comment by corydeppen** [comment]
@jaredpalmer Unfortunately, this will cause a compilation error since the latest typings for node don't include a `hot` property on the `NodeModule` type.

**Comment by jaredpalmer** [comment]
Just add @types/webpack-env

**Comment by jaredpalmer** [comment]
`@types/webpack-env`

**Comment by Lxxyx** [comment]
or you can use (module as any).hot.accept() @corydeppen

**Comment by NeekSandhu** [comment]
Maybe you're looking for this, since you mentioned losing state

https://github.com/gaearon/react-hot-loader

**Comment by nikhilyeole1** [comment]
Hot reload doesn't work for me. I have opened new issue.
https://github.com/Microsoft/TypeScript-React-Starter/issues/50

**Comment by priyanshuchauhan** [comment]
- npm install react-hot-loader --save-dev
- npm install --save-dev @types/webpack-env

In index.tsx: 

```
(module as any).hot.accept();

ReactDOM.render(
  <App />,
  document.getElementById('root') as HTMLElement
);
```
