### ISSUE TITLE
(33,5): error TS2687: All declarations of 'value' must have identical modifiers.

### ISSUE THREAD

**Issue by aprtm** [Microsoft/TypeScript-React-Starter#67]
Error comes from /node_modules/typescript/lib/lib.es2015.iterable.d.ts
Throws right after `create-react-app my-app --scripts-version=react-scripts-ts` is done with no warnings or errors, when executing yarn start. I am on a mac with OSX Yosemite 10.10.5 using create-react-app version 1.4.1, tsc version 2.3.2 and yarn version 1.1.0.

**Comment by aprtm** [comment]
I finally figured out what was causing the problem. There was a node_modules folder somewhere up the directory tree. Removing the folder solved the issue.

**Comment by jonaswouters** [comment]
@aprtm Can you be more specific what you did?

**Comment by aprtm** [comment]
@jonaswouters I was working within a folder that had a backup copy of the node_modules for another project. The older project might have used Angular (2+).
I did not notice it before because the backup was at the root of the test project, 3 levels above of where I created my react application.

**Comment by geewhizbang** [comment]
npm prune worked for me
