### ISSUE TITLE
please allow js/jsx components

### ISSUE THREAD

**Issue by agdolla** [Microsoft/TypeScript-React-Starter#72]
Hi
I'm developing my project in typescript with this starter but I'd like to have a few components to be written in js/jsx. Currently it does not work, I receive strange error like this:

```
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/Alma.60238e91.jsx') is not a valid name.
```

**Comment by ccaseiro** [comment]
Not fixed yet? I'm having the same problem :(

**Comment by miller-time** [comment]
Have you tried just renaming the js/jsx component filenames from .js to .ts (or .jsx to .tsx)? JavaScript is perfectly valid TypeScript :grin:

**Comment by mascardoso** [comment]
@agdolla were you able to fix this? I have the same issue.
