### ISSUE TITLE
Readme is confusing

### ISSUE THREAD

**Issue by cdoremus** [Microsoft/TypeScript-React-Starter#9]
I'm confused. Is this repo the result of using create-react-app with the react-scripts-ts script? Or should you use CRA and the react-script-ts script on top of this repo? Please advise.

**Comment by DanielRosenwasser** [comment]
You should follow the README steps to get to the content of this repo itself. You can easily clone the repo to try out the resulting repo.

**Comment by cdoremus** [comment]
Thank you. You should make that clear in the Readme.
